- name: Get host information
  hosts: all  
  become: yes
  
  tasks: 
  #
  # Display message with host information
  # =====================================
    - name: Get os kernel version release 
      command: uname -osr
      register: oskernelrelease

    - name: Check httpd installation  
      yum:
        list: httpd
      register: httpdcheck

    - name: Display host information
      vars:
        hostOS: "{{ hostvars[inventory_hostname].ansible_distribution }}"
        hostCores: "{{ hostvars[inventory_hostname].ansible_processor_cores }}"
        hostMemTotal: "{{ hostvars[inventory_hostname].ansible_memtotal_mb }}"
        hostMemFree: "{{ hostvars[inventory_hostname].ansible_memfree_mb }}"
        demo_message: "Hello World!"
      debug:
        msg:
          - "Message from: {{ inventory_hostname }} - {{ demo_message }}"
          - "OS: {{ hostOS }}, Cores: {{ hostCores }}, Memory: {{ hostMemTotal }}, Free: {{ hostMemFree }}"
          - "kernel: {{ oskernelrelease.stdout_lines }}"
          - "http server: {{ httpdcheck }}"
          

  #
