- name: Hello World Sample
  hosts: all
  
  tasks:
  # Pause for x minutes
  # ===================
    - name: Pause for x minute before running the tasks
      pause:
        minutes: 0
  #
  # Display message with host information
  # Cannot display custom fact if not created yet.
  # =====================================
    - name: Hello Message 
      vars:
        hostOS: "{{ hostvars[inventory_hostname].ansible_distribution }}"
        hostCores: "{{ hostvars[inventory_hostname].ansible_processor_cores }}"
        hostMemTotal: "{{ hostvars[inventory_hostname].ansible_memtotal_mb }}"
        hostMemFree: "{{ hostvars[inventory_hostname].ansible_memfree_mb }}"
        demo_message: "Hello World!"
      debug:
        msg:
          - "Message from: {{ inventory_hostname }} - {{ demo_message }}"
          - "OS: {{ hostOS }}, Cores: {{ hostCores }}, Memory: {{ hostMemTotal }}, Free: {{ hostMemFree }}"
          - "23-July-2021 Run 1"

  #
  # Custom fact created using facts.d will be available in next play that gathers facts. 
  # To use it in the same play where you created it, you must explicitly re-run the setup module.
  # Get/Set Custom Facts  
  # ====================
  
    - name: Create directory for ansible custom facts
      ansible.builtin.file:
        state: directory
        recurse: yes
        path: /etc/ansible/facts.d
              
    - name: Create a new file with permissions
      file:
        path: "/etc/ansible/facts.d/custom03.fact"
        state: absent
        mode: 0664

    - name: Insert block of configuration custom information  
      blockinfile:
        path: /etc/ansible/facts.d/custom03.fact
        create: yes
        mode: 0664
        marker: ""
        marker_begin: ""
        marker_end: ""
        block: |
          {
            "packages": {
              "web_package": "httpd",
              "db_package": "mariadb-server"
            },
            "users": {
              "user1": "joe",
              "user2": "jane"
            }
          }          

#
# ansible localhost -m setup | grep custom -A 5 
# ansible localhost -m ansible.builtin.setup -a "filter=ansible_local"
#        
#    - name: "Re-run setup to use custom facts"
#      setup: ~

# Get custom facts
# =====================================
#    - name: Custom Facts 
#      vars:
#        customFactUser1: "{{ hostvars[inventory_hostname].ansible_local.custom01.users.user1 }}"
#        customFactUsers: "{{ hostvars[inventory_hostname].ansible_local.custom01.users }}"
#      debug:
#        msg:
#          - "Custom facts: {{ customFactUsers }} - {{ customFactUser1 }}"



