- name: Hello World Sample
  hosts: all
  tasks:
  # Pause for x minutes to build app cache.
    - name: Pause for x minute before running the tasks
      pause:
        minutes: 0
    - name: Hello Message
      vars:
        hostOS: "{{ hostvars[inventory_hostname].ansible_distribution }}"
        hostCores: "{{ hostvars[inventory_hostname].ansible_processor_cores }}"
        hostMemTotal: "{{ hostvars[inventory_hostname].ansible_memtotal_mb }}"
        hostMemFree: "{{ hostvars[inventory_hostname].ansible_memfree_mb }}"
      debug:
        msg: 
          - "{{ inventory_hostname }} - Hello World! {{ demo_message }}"
          - "OS: {{ hostOS }}, Cores: {{ hostCores }}, Memory: {{ hostMemTotal }}, Free: {{ hostMemFree }}"
          
