- name: Hello World Sample
  hosts: all
  
  tasks:
  # Pause for x minutes
  # ===================
    - name: Pause for x minute before running the tasks
      pause:
        minutes: 0
  #
  # Display message with host information
  # =====================================
    - name: Hello Message 
      vars:
        hostOS: "{{ hostvars[inventory_hostname].ansible_distribution }}"
        hostCores: "{{ hostvars[inventory_hostname].ansible_processor_cores }}"
        hostMemTotal: "{{ hostvars[inventory_hostname].ansible_memtotal_mb }}"
        hostMemFree: "{{ hostvars[inventory_hostname].ansible_memfree_mb }}"
        customFact01: "{{ hostvars[inventory_hostname].ansible_local.* }}"
        demo_message: "Hello World!"
      debug:
        msg:
          - "Message from: {{ inventory_hostname }} - {{ demo_message }}"
          - "OS: {{ hostOS }}, Cores: {{ hostCores }}, Memory: {{ hostMemTotal }}, Free: {{ hostMemFree }}"
          - "13-Dec-2020 Run 1"

  #
  # Custom fact created using facts.d will be available in next play that gathers facts. 
  # To use it in the same play where you created it, you must explicitly re-run the setup module.
  # Get/Set Custom Facts  
  # ====================
  
    - name: Create directory for ansible custom facts
      ansible.builtin.file:
        state: directory
        recurse: yes
        path: /etc/ansible/facts.d

    - name: Create a static custom fact
      copy:
        content: '"customfact01": { "var01" : "123", "var02"  : "abc" }"'
        dest: /etc/ansible/facts.d/custom_fact01.fact

    - name: "Re-run setup to use custom facts"
      setup: ~
      vars:
        customFact01: "{{ hostvars[inventory_hostname].ansible_local.* }}"
      debug:
        msg: 
          - "Custom Facts: {{ customFact01 }}"
