## Credits to John Lieske - https://www.ansible.com/blog/getting-started-writing-your-first-playbook
## https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html
---
- name: Install nginx
  hosts: web1
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
