- name: Yum Install
  hosts: all
  tasks:
    - name: install one specific version of nano
      yum:
        name: nano
        state: present
      become: true

    - name: upgrade packages, exclude kernel & foo related packages
      yum:
        name: 'nano*'
        state: latest
        exclude: kernel*,foo*
      become: true

    - name: verify installation
      shell: /usr/bin/nano -V || grep GNU
      register: cmd_result
      
    - fail:
        msg: 'nano installation failed'
      when: "'GNU' not in cmd_result.content"
